### ISSUE TITLE
munihac.de is currently down

### ISSUE THREAD

**Issue by andys8** [munihac/munihac.github.io#1]
Hey, looking forward to Munihac 2018.

The page can currently not be accessed via the official domain and/or coming from Google. 

- https://munihac.github.io is working
- http://munihac.de is down
- http://www.munihac.de returns 404

![screenshot_20180813-225720](https://user-images.githubusercontent.com/13085980/44060430-97ad41f8-9f4c-11e8-9eaf-4be7803eb912.png)
![screenshot_20180813-225645](https://user-images.githubusercontent.com/13085980/44060500-c4893466-9f4c-11e8-94c4-aa6682f55786.png)

**Comment by afwlehmann** [comment]
Sorry for the late reply. We've had to reconfigure some DNS records due to the fact that we moved the hosting of this website from a proprietary TNG server to GitHub. Thanks for reporting though!
